// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: proto/dict.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DictResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rc         int32                    `protobuf:"varint,1,opt,name=rc,proto3" json:"rc,omitempty"`
	Dictionary *DictResponse_Dictionary `protobuf:"bytes,2,opt,name=dictionary,proto3" json:"dictionary,omitempty"`
}

func (x *DictResponse) Reset() {
	*x = DictResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dict_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictResponse) ProtoMessage() {}

func (x *DictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dict_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictResponse.ProtoReflect.Descriptor instead.
func (*DictResponse) Descriptor() ([]byte, []int) {
	return file_proto_dict_proto_rawDescGZIP(), []int{0}
}

func (x *DictResponse) GetRc() int32 {
	if x != nil {
		return x.Rc
	}
	return 0
}

func (x *DictResponse) GetDictionary() *DictResponse_Dictionary {
	if x != nil {
		return x.Dictionary
	}
	return nil
}

type DictRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransType string `protobuf:"bytes,1,opt,name=trans_type,json=transType,proto3" json:"trans_type,omitempty"`
	Source    string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	UserId    string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DictRequest) Reset() {
	*x = DictRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dict_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictRequest) ProtoMessage() {}

func (x *DictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dict_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictRequest.ProtoReflect.Descriptor instead.
func (*DictRequest) Descriptor() ([]byte, []int) {
	return file_proto_dict_proto_rawDescGZIP(), []int{1}
}

func (x *DictRequest) GetTransType() string {
	if x != nil {
		return x.TransType
	}
	return ""
}

func (x *DictRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DictRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DictResponse_Wiki struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DictResponse_Wiki) Reset() {
	*x = DictResponse_Wiki{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dict_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictResponse_Wiki) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictResponse_Wiki) ProtoMessage() {}

func (x *DictResponse_Wiki) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dict_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictResponse_Wiki.ProtoReflect.Descriptor instead.
func (*DictResponse_Wiki) Descriptor() ([]byte, []int) {
	return file_proto_dict_proto_rawDescGZIP(), []int{0, 0}
}

type DictResponse_Dictionary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prons        *DictResponse_Dictionary_Prons     `protobuf:"bytes,1,opt,name=prons,proto3" json:"prons,omitempty"`
	Explanations []string                           `protobuf:"bytes,2,rep,name=explanations,proto3" json:"explanations,omitempty"`
	Synonym      []string                           `protobuf:"bytes,3,rep,name=synonym,proto3" json:"synonym,omitempty"`
	Antonym      []string                           `protobuf:"bytes,4,rep,name=antonym,proto3" json:"antonym,omitempty"`
	WqxExample   []*DictResponse_Dictionary_Example `protobuf:"bytes,6,rep,name=wqx_example,json=wqxExample,proto3" json:"wqx_example,omitempty"`
	Entry        string                             `protobuf:"bytes,7,opt,name=entry,proto3" json:"entry,omitempty"`
	Type         string                             `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	Related      []string                           `protobuf:"bytes,9,rep,name=related,proto3" json:"related,omitempty"`
	Source       string                             `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *DictResponse_Dictionary) Reset() {
	*x = DictResponse_Dictionary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dict_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictResponse_Dictionary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictResponse_Dictionary) ProtoMessage() {}

func (x *DictResponse_Dictionary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dict_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictResponse_Dictionary.ProtoReflect.Descriptor instead.
func (*DictResponse_Dictionary) Descriptor() ([]byte, []int) {
	return file_proto_dict_proto_rawDescGZIP(), []int{0, 1}
}

func (x *DictResponse_Dictionary) GetProns() *DictResponse_Dictionary_Prons {
	if x != nil {
		return x.Prons
	}
	return nil
}

func (x *DictResponse_Dictionary) GetExplanations() []string {
	if x != nil {
		return x.Explanations
	}
	return nil
}

func (x *DictResponse_Dictionary) GetSynonym() []string {
	if x != nil {
		return x.Synonym
	}
	return nil
}

func (x *DictResponse_Dictionary) GetAntonym() []string {
	if x != nil {
		return x.Antonym
	}
	return nil
}

func (x *DictResponse_Dictionary) GetWqxExample() []*DictResponse_Dictionary_Example {
	if x != nil {
		return x.WqxExample
	}
	return nil
}

func (x *DictResponse_Dictionary) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

func (x *DictResponse_Dictionary) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DictResponse_Dictionary) GetRelated() []string {
	if x != nil {
		return x.Related
	}
	return nil
}

func (x *DictResponse_Dictionary) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type DictResponse_Dictionary_Prons struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnUs string `protobuf:"bytes,1,opt,name=en_us,json=enUs,proto3" json:"en_us,omitempty"`
	En   string `protobuf:"bytes,2,opt,name=en,proto3" json:"en,omitempty"`
}

func (x *DictResponse_Dictionary_Prons) Reset() {
	*x = DictResponse_Dictionary_Prons{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dict_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictResponse_Dictionary_Prons) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictResponse_Dictionary_Prons) ProtoMessage() {}

func (x *DictResponse_Dictionary_Prons) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dict_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictResponse_Dictionary_Prons.ProtoReflect.Descriptor instead.
func (*DictResponse_Dictionary_Prons) Descriptor() ([]byte, []int) {
	return file_proto_dict_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *DictResponse_Dictionary_Prons) GetEnUs() string {
	if x != nil {
		return x.EnUs
	}
	return ""
}

func (x *DictResponse_Dictionary_Prons) GetEn() string {
	if x != nil {
		return x.En
	}
	return ""
}

type DictResponse_Dictionary_Example struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExampleStrings []string `protobuf:"bytes,1,rep,name=example_strings,json=exampleStrings,proto3" json:"example_strings,omitempty"`
}

func (x *DictResponse_Dictionary_Example) Reset() {
	*x = DictResponse_Dictionary_Example{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dict_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictResponse_Dictionary_Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictResponse_Dictionary_Example) ProtoMessage() {}

func (x *DictResponse_Dictionary_Example) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dict_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictResponse_Dictionary_Example.ProtoReflect.Descriptor instead.
func (*DictResponse_Dictionary_Example) Descriptor() ([]byte, []int) {
	return file_proto_dict_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *DictResponse_Dictionary_Example) GetExampleStrings() []string {
	if x != nil {
		return x.ExampleStrings
	}
	return nil
}

var File_proto_dict_proto protoreflect.FileDescriptor

var file_proto_dict_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x69, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xfe, 0x03, 0x0a, 0x0c, 0x44, 0x69, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x72, 0x63, 0x12, 0x38, 0x0a, 0x0a, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72,
	0x79, 0x52, 0x0a, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x1a, 0x06, 0x0a,
	0x04, 0x57, 0x69, 0x6b, 0x69, 0x1a, 0x9b, 0x03, 0x0a, 0x0a, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x72, 0x79, 0x12, 0x34, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x50, 0x72,
	0x6f, 0x6e, 0x73, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6e, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x78,
	0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0c, 0x65, 0x78, 0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x79, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x79, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6e, 0x74, 0x6f,
	0x6e, 0x79, 0x6d, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6e, 0x74, 0x6f, 0x6e,
	0x79, 0x6d, 0x12, 0x41, 0x0a, 0x0b, 0x77, 0x71, 0x78, 0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72,
	0x79, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x0a, 0x77, 0x71, 0x78, 0x45, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x1a, 0x2c, 0x0a, 0x05, 0x50, 0x72, 0x6f, 0x6e, 0x73, 0x12, 0x13, 0x0a, 0x05, 0x65, 0x6e,
	0x5f, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x65, 0x6e, 0x55, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x65, 0x6e, 0x1a,
	0x32, 0x0a, 0x07, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x73, 0x22, 0x5d, 0x0a, 0x0b, 0x44, 0x69, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x32, 0x33, 0x0a, 0x07, 0x53, 0x61, 0x79, 0x44, 0x69, 0x63, 0x74, 0x12, 0x28, 0x0a,
	0x07, 0x53, 0x61, 0x79, 0x44, 0x69, 0x63, 0x74, 0x12, 0x0c, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_dict_proto_rawDescOnce sync.Once
	file_proto_dict_proto_rawDescData = file_proto_dict_proto_rawDesc
)

func file_proto_dict_proto_rawDescGZIP() []byte {
	file_proto_dict_proto_rawDescOnce.Do(func() {
		file_proto_dict_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_dict_proto_rawDescData)
	})
	return file_proto_dict_proto_rawDescData
}

var file_proto_dict_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_dict_proto_goTypes = []interface{}{
	(*DictResponse)(nil),                    // 0: DictResponse
	(*DictRequest)(nil),                     // 1: DictRequest
	(*DictResponse_Wiki)(nil),               // 2: DictResponse.Wiki
	(*DictResponse_Dictionary)(nil),         // 3: DictResponse.Dictionary
	(*DictResponse_Dictionary_Prons)(nil),   // 4: DictResponse.Dictionary.Prons
	(*DictResponse_Dictionary_Example)(nil), // 5: DictResponse.Dictionary.Example
}
var file_proto_dict_proto_depIdxs = []int32{
	3, // 0: DictResponse.dictionary:type_name -> DictResponse.Dictionary
	4, // 1: DictResponse.Dictionary.prons:type_name -> DictResponse.Dictionary.Prons
	5, // 2: DictResponse.Dictionary.wqx_example:type_name -> DictResponse.Dictionary.Example
	1, // 3: SayDict.SayDict:input_type -> DictRequest
	0, // 4: SayDict.SayDict:output_type -> DictResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_dict_proto_init() }
func file_proto_dict_proto_init() {
	if File_proto_dict_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_dict_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dict_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dict_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictResponse_Wiki); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dict_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictResponse_Dictionary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dict_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictResponse_Dictionary_Prons); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dict_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictResponse_Dictionary_Example); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_dict_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dict_proto_goTypes,
		DependencyIndexes: file_proto_dict_proto_depIdxs,
		MessageInfos:      file_proto_dict_proto_msgTypes,
	}.Build()
	File_proto_dict_proto = out.File
	file_proto_dict_proto_rawDesc = nil
	file_proto_dict_proto_goTypes = nil
	file_proto_dict_proto_depIdxs = nil
}
